### ISSUE TITLE
Test dependencies are included in other environments

### ISSUE THREAD

**Issue by A-Legg** [neilberkman/docusign_elixir#18]
Thanks so much for the hard work you've put into the library! I'd like to add it to my application but prefer to only include test dependencies in the test environment. After attempting to include this library I am forced to include mock in non-test environments. Any chance you can only include mock and bypass in the test environment?

**Comment by neilberkman** [comment]
Sorry, I don't have time to do this work myself. I'd be happy to accept a PR.

**Comment by neilberkman** [comment]
hi @A-Legg - FYI I merged in a few of your commits and published an update. Thanks for your contributions!

**Comment by A-Legg** [comment]
Hey @neilberkman! I don't recall the motivation for some of these changes or know how you got your hand on them but hope you're having a Joyful end of the year, cheers!
