### ISSUE TITLE
Unable to autofill Text Tabs via the DocuSign API.

### ISSUE THREAD

**Issue by fteln0v** [neilberkman/docusign_elixir#19]
# Environment
* Elixir version (elixir -v): 1.11.2
* Phoenix version (mix deps): 1.5.7
* Phoenix LiveView version (mix deps): 0.15.0
* NodeJS version (node -v): 14.5.1
* NPM version (npm -v): 6.14.9
* Operating system: Mac OSX Big Sur
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome

# Description
I’m trying to autofill a template via the DocuSign API using the ```docusign_elixir_sample_app``` as a guide. The template’s role is set to “signer”, and contains the following tabs:

- Radio (Group Label = Radio Group)
- Checkbox (Data Label = Checkbox)
- Text (Data Label = Name)

The API call succeeds when I run the ```radio_group``` and ```checkbox``` models in isolation (by omitting the ```text_tabs``` model), however when I add the ```text_tabs``` model, I get an ```INVALID_REQUEST_PARAMETER``` error. Is there an issue with my ```text_tabs``` model, as the other two work?

# My code
```
defmodule MyApp.DocuSignUploader do
  alias DocuSign.Api

  @template_id "xxxxxxxxxxxxxxxxxxxx"

  def send_envelope do
    checkbox =
      %DocuSign.Model.Checkbox{
        tabLabel: "Checkbox",
        selected: true
      }

    radio =
      %DocuSign.Model.Radio{
        selected: true,
        value: "Radio1"
      }

    radio_group =
      %DocuSign.Model.RadioGroup{
        groupName: "Radio Group",
        radios: [radio]
      }

    text_tabs =
      %DocuSign.Model.Text{
        tabLabel: "Name",
        value: "Value inserted via api",
      }

    tabs =
      %DocuSign.Model.EnvelopeRecipientTabs{
        checkboxTabs: [checkbox],
        radioGroupTabs: [radio_group],
        textTabs: [text_tabs]
      }

    signer =
      %DocuSign.Model.TemplateRole{
        email: "test@email.com",
        name: "Some Name",
        roleName: "signer",
        tabs: tabs
      }

    definition =
      %DocuSign.Model.EnvelopeDefinition{
        emailSubject: "Some email subject",
        templateId: @template_id,
        templateRoles: [signer],
        status: "sent"
      }

    case Api.Envelopes.envelopes_post_envelopes(connection(), account_id(),
      envelopeDefinition: definition
         ) do
      {:ok, %DocuSign.Model.EnvelopeSummary{} = envelope_summary} ->
        envelope_summary

      {:error, %Tesla.Env{body: error}} ->
        {:error, error}
    end
  end

  defp connection, do: DocuSign.Connection.new(client: DocuSign.APIClient.client())

  defp account_id, do: Application.get_env(:docusign, :account_id)
end

```

# Actual behavior
```
MyApp.send_envelope()
..

{:error,
 "{\r\n  \"errorCode\": \"INVALID_REQUEST_PARAMETER\",\r\n  \"message\": \"The request contained at least one invalid parameter. Invalid value specified for 'templateId'\"\r\n}"}
```

# Expected behavior
The send_envelope function should autofill all three tabs.

**Comment by neilberkman** [comment]
Thanks for the bug report. Unfortunately I don't have much time to maintain this project but I'm happy to accept and integrate PRs.

**Comment by fteln0v** [comment]
Thanks for writing this useful library! I'll close the issue as it wasn't a bug with the library.

For anyone else experiencing the same problem: In order to pre-fill Text Tabs using the DocuSign API, the solution is to not leave any of the integer fields (height, width, maxLength) blank:
```
text_tabs =
      %DocuSign.Model.Text{
        tabLabel: "Name",
        value: "Value inserted via api",
        height: 11,
        width: 90,
        maxLength: 4000
      }
```

**Comment by neilberkman** [comment]
Awesome, thanks @fteln0v !
