### ISSUE TITLE
Returning timeout

### ISSUE THREAD

**Issue by aramsm** [neilberkman/docusign_elixir#22]
Hi there,

I'm getting `{:error, :timeout}` very often with `DocuSign.Api.Envelopes.envelopes_post_envelopes/3`, but the thing is the envelopes were sent and I got them on my e-mails. Is there a way to fix this? A setting maybe?

Thanks in advance.

**Comment by aramsm** [comment]
If you are reading this, we solved it by doing this https://github.com/igraguiar/docusign_elixir/commit/4a5fbe2a7ee78b59fe1ba9737f44722c560ce617

**Comment by neilberkman** [comment]
Fixed in https://github.com/neilberkman/docusign_elixir/commit/c23beafdafccd53f3caa783a971de82a11a77383

**Comment by neilberkman** [comment]
Now _actually_ fixed in https://github.com/neilberkman/docusign_elixir/pull/27 🙂
