### ISSUE TITLE
How to not require consent (:consent_required) for a cli app

### ISSUE THREAD

**Issue by ghenry** [neilberkman/docusign_elixir#38]
Hi,

First of all, thanks for creating this!

I'm just testing things and following:

https://github.com/neilberkman/docusign_elixir/tree/main#configuring-docusign

You say _If you want, you can use your administrator user with the API._ If doing this, should I still have to do the OAuth2 dance?

I'm getting this (so I know all is working):

```
iex(2)> {:ok, conn} = DocuSign.Connection.get(user_id)

14:45:30.953 [warning] Description: ~c"Server authenticity is not verified since certificate path validation is not enabled"
     Reason: ~c"The option {verify, verify_peer} and one of the options 'cacertfile' or 'cacerts' are required to enable this."

** (MatchError) no match of right hand side value: {:error, {:consent_required, "Ask user to visit this URL to consent impersonation: https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=XXXX&redirect_uri=https://account-d.docusign.com/me"}}
    (stdlib 4.3.1.2) erl_eval.erl:496: :erl_eval.expr/6
    iex:2: (file)
```

I'm doing this as a cli app and don't want to do the redirect. Or if I have to, I'm not sure how to grab that redirect (even if I configured it in the DocuSign settings) on the cli

Thanks,
Gavin.

**Comment by ghenry** [comment]
FYI, this is for a **docusign_backup** oss app I'm putting on GitHub to do:

https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/list/

then

https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopedocuments/get/

to export all your combined signed docs in PDF.

Thanks.

**Comment by neilberkman** [comment]
Hi @ghenry I don't know offhand but I'll take a look when I have some time.

**Comment by ghenry** [comment]
Thanks! https://github.com/ghenry/docusign_backup

**Comment by ghenry** [comment]
One last question, why do we need to create a private key (Service Integration) if we're doing the Oauth2 dance to impersonate? I must have missed a step if it's asking this of me as I'm using the admin account User ID.

**Comment by ghenry** [comment]
Ah, I should read the docs - https://developers.docusign.com/platform/auth/jwt/ is the flow you're doing for a systems integration method.

**Comment by ghenry** [comment]
And I missed this demo app! https://github.com/neilberkman/docusign_elixir_sample_app

I'll shut up now. Thanks.

**Comment by neilberkman** [comment]
@ghenry no problem, actually I'm sure the demo app needs to be updated. I've published a new version , 1.1.1, with all dependencies updated.

**Comment by ghenry** [comment]
No matter what I do I'm getting asked for consent even though I'm setting the user_id to the admin user id:

```
iex(5)> {:ok, conn} = DocuSign.Connection.get(user_id)  
** (MatchError) no match of right hand side value: {:error, {:consent_required, "Ask user to visit this URL to consent impersonation: https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=XXXX&redirect_uri=https://account-d.docusign.com/me"}}
    (stdlib 4.3.1.2) erl_eval.erl:496: :erl_eval.expr/6
    iex:5: (file)
```

**Comment by ghenry** [comment]
More progress. First when I clicked the link in the "consent_required" phase, DocuSign side my app didn't have a Redirect URI set. I've sent one and have a Phoenix basic app listening to see what comes in, but instead I get:

![Screenshot 2023-09-14 at 16-45-24 DocuSign](https://github.com/neilberkman/docusign_elixir/assets/159608/22f25bbd-8521-4d65-85a2-c88b511e2a8e)

so this is confusing now.

**Comment by ghenry** [comment]
FFS. After reading https://developers.docusign.com/platform/auth/jwt/jwt-get-token/ and then your README again, I have not set the Redirect URI to match what you link generates and what YOU LIST IN THE DOCs (https://github.com/neilberkman/docusign_elixir#configuring-docusign) :-)

My bad.

**Comment by ghenry** [comment]
Testing again.
