### ISSUE TITLE
Workflow for making this multi-tenant/user

### ISSUE THREAD

**Issue by ghenry** [neilberkman/docusign_elixir#39]
Hi @neilberkman 

What workflow would you recommend I follow if I want to connect as different users?

So let's say I have a Phoenix app and I need to call `{:ok, conn} = DocuSign.Connection.get(user_id)` via an Oban worker or one-off job for example.

To get consent I need to first get the **user_id** then I could save the **conn** struct against a user in a db table etc. Should I just prompt a user for their **user_id** with some in context help or is there a slicker way via a proper DocuSign app directory integration or something?

I'll have a read of their developer guide, but I'm sure you've done this as you created this lib :-)

Thanks,
Gavin.

**Comment by neilberkman** [comment]
@ghenry honestly I haven't. I created the library years ago when I needed it for a project but haven't used it myself in years. Again, happy to take a look when I have time but your quickest path is likely to be to read the docs.

**Comment by ghenry** [comment]
No worries. I'll update this when I figure it out. Thanks for listening!
