### ISSUE TITLE
Providing contents of private key as environment variable

### ISSUE THREAD

**Issue by maartenJacobs** [neilberkman/docusign_elixir#40]
Hi,

Is there a way of providing the contents of the private key as an environment variable? Based on a small sample size, for sure, but environments I work on don't tend to write files for configuration. All configuration comes from environment variables.

As a workaround, I've set `token_signer` in config to something like `Joken.Signer.create("RS256", %{"pem" => System.fetch_env!("DOCUSIGN_PRIVATE_KEY")})`.

I guess ideally `private_key` would be the file contents and `private_key_file` would be the file path, and either one is provided. But I realise that's difficult to introduce for existing users of this library.

Thanks,
Maarten

**Comment by neilberkman** [comment]
@maartenJacobs there's not. A PR for a backwards-compatible solution would be welcome.

**Comment by maartenJacobs** [comment]
@neilberkman Happy to prepare a PR 👍 

Do you have any preference for the configuration? I have some ideas below. These are all backwards compatible but some add warning messages or change the behaviour.

* `private_key` can be a private key file, the contents of the private key, or a `Joken.Signer` struct. This package would need to detect the intent of the configuration value and set `token_signer` accordingly. There is a possibility that the detection is faulty and files are used as contents, and/or vice versa.
* `private_key` remains as-is and `private_key_contents` is added to accept the contents of the private key. If both are use, log a warning and prefer the file. If none are used, same behaviour as current.
* `private_key` can be a string which would be the private key file, `{:file, "/some/location"}` which would also be the private key file, or `{:key, "--- private key --- ..."}` which would be the contents.
* `private_key` continues working but gets deprecated, `private_key_file` and `private_key_contents` are added. Either one can be set but not both.

**Comment by neilberkman** [comment]
@maartenJacobs, thanks. I think that the last option would be the cleanest and most future-proof. It's important that we provide clear and concise documentation about these changes to ensure a smooth transition for existing users. This should include detailed notices in the release notes, and ideally some notes on migration. Once this is merged, I'll bump the version to `1.2.0` to reflect the new features and deprecations.

**Comment by maartenJacobs** [comment]
Thanks @neilberkman, I'll put up a PR before end of February 🤞

**Comment by maartenJacobs** [comment]
This is included in 1.2.0 so this issue is resolved. Thanks @neilberkman 🙌
