### ISSUE TITLE
Webhook plug

### ISSUE THREAD

**Issue by maartenJacobs** [neilberkman/docusign_elixir#42]
Would this repository be a good place for a webhook plug in the style of https://hexdocs.pm/stripity_stripe/Stripe.WebhookPlug.html? I'm looking into receiving webhooks from DocuSign and hoping to share the implementation, specifically for requests signed with HMAC.

If so I'm happy to provide a PR .

**Comment by neilberkman** [comment]
@maartenJacobs Yes, I'd love to provide webhook support within this package! I would appreciate a PR.

**Comment by maartenJacobs** [comment]
Thanks @neilberkman, I've created #43 now

**Comment by neilberkman** [comment]
Excellent, I’ll take a look at it soon!

**Comment by maartenJacobs** [comment]
Included in 1.1.3 so closing this. Thanks @neilberkman 🙌
